# Generated by Django 4.2.1 on 2023-05-21 19:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='events/')),
                ('event_type', models.CharField(choices=[('MARRIAGE', 'marriage'), ('BIRTHDAY', 'birthday'), ('FUNERAL', 'funeral'), ('ENGAREMENT', 'engagement'), ('BAPTISM', 'baptism'), ('HOUSE WARMING', 'house warming')], max_length=255)),
                ('event_date', models.DateField(max_length=64)),
                ('single_time', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
            ],
        ),
    ]
